---
# tasks/main.yml for Jenkins role

- name: Install required dependencies
  apt:
    name:
      - curl
      - gnupg
      - software-properties-common
      - ca-certificates
    state: present
    update_cache: yes

- name: Create directory for Jenkins GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    dest: /etc/apt/keyrings/jenkins.gpg
    mode: '0644'

- name: Add Jenkins repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/jenkins.gpg] https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes