---
- hosts: web
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: latest
        update_cache: yes

    - name: Create document root
      file:
        path: "/var/www/html"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'

    - name: Deploy index.html
      copy:
        src: "index.html"
        dest: "/var/www/html/index.html"
        owner: "www-data"
        group: "www-data"
        mode: '0644'

    - name: Enable Apache service
      service:
        name: apache2
        enabled: yes
        state: started

    - name: Allow HTTP traffic
      ufw:
        rule: allow
        port: "80"
        proto: tcp